name: ci

on: 
  push:
    branches:
      - master
    
jobs:
    
    ci:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.102

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@master

      - name: Create nuget config file
        run: |
         nuget_config='<?xml version="1.0" encoding="utf-8"?>
                            <configuration>
                                <packageSources>
                                    <clear />
                                    <add key="github" value="https://nuget.pkg.github.com/aaronlcope/index.json" />
                                    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
                                </packageSources>
                                <packageSourceCredentials>
                                    <github>
                                        <add key="Username" value="aaroncope@gmail.com" />
                                        <add key="ClearTextPassword" value="${{ secrets.PACKAGE_TOKEN }}" />
                                    </github>
                                </packageSourceCredentials>
                            </configuration>'
           echo "$nuget_config" > ./src/NuGet.config

      - name: Run CI script
        run: ./scripts/ci.sh --skip-unit-tests --skip-sonar-cloud-analysis --skip-nuget-packaging --sonar-cloud-auth-token ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_PATH: ${ GITHUB_EVENT_PATH }

      - name: Publish application for distribution (windows).
        run: |
         dotnet publish ./src/*.csproj -c Release -r win-x64
         zip -r win-x64.zip ./bin/Release/netcoreapp3.1/win-x64

      - name: Publish application for distribution (linux).
        run: |
         dotnet publish ./src/*.csproj -c Release -r linux-x64
         zip -r linux-x64.zip ./bin/Release/netcoreapp3.1/linux-x64

      - name: Publish application for distribution (osx).
        run: |
         dotnet publish ./src/*.csproj -c Release -r osx-x64
         zip -r osx-x64.zip ./bin/Release/netcoreapp3.1/osx-x64

      - name: Upload build artifact (windows)
        uses: actions/upload-artifact@master
        with:
            name: win-x64.zip
            path: ./bin/Release/netcoreapp3.1/win-x64

      - name: Upload build artifact (linux)
        uses: actions/upload-artifact@master
        with:
            name: linux-x64.zip
            path: ./bin/Release/netcoreapp3.1/linux-x64

      - name: Upload build artifact (osx)
        uses: actions/upload-artifact@master
        with:
            name: osx-x64.zip
            path: ./bin/Release/netcoreapp3.1/osx-x64