name: ci

on: 
  push:
    branches:
      - master
    
jobs:
    
    ci:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.102

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@master

      - name: Run CI script
        run: ./scripts/ci.sh --skip-unit-tests --skip-sonar-cloud-analysis --sonar-cloud-auth-token ${{ secrets.SONAR_TOKEN }} --skip-nuget-packaging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_PATH: ${ GITHUB_EVENT_PATH }

      - name: Publish application for distribution.
        run: |
        local output_path="./bin/Release/netcoreapp3.1"
        dotnet publish --framework netcoreapp3.1 --runtime win-x64
        dotnet publish --framework netcoreapp3.1 --runtime linux-x64
        dotnet publish --framework netcoreapp3.1 --runtime osx-x64
        zip -r win-x64.zip '$output_path/win-x64'
        zip -r win-x64.zip '$output_path/linux-x64'
        zip -r win-x64.zip '$output_path/osx-x64'

      - name: Upload build artifact (windows)
        uses: actions/upload-artifact@master
        with:
            name: win-x64.zip
            path: ./bin/Release/netcoreapp3.1/win-x64

      - name: Upload build artifact (linux)
        uses: actions/upload-artifact@master
        with:
            name: linux-x64.zip
            path: ./bin/Release/netcoreapp3.1/linux-x64

      - name: Upload build artifact (osx)
        uses: actions/upload-artifact@master
        with:
            name: osx-x64.zip
            path: ./bin/Release/netcoreapp3.1/osx-x64